name: translate

# Controls when the workflow will run
on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  translate:
    uses: Mips2648/jeedom-translations/.github/workflows/translations.yml@main
