name: translate

# Controls when the workflow will run
on:
  workflow_dispatch:

  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta

jobs:
  translate:
    uses: Mips2648/jeedom-translations/.github/workflows/translations.yml@main
